"""Beets CLI wrapper and inbox DB reader."""
from __future__ import annotations

import sqlite3
import subprocess
from pathlib import Path
from typing import Any

from ..config import Config

# ── Config generation ──────────────────────────────────────────────────────────

_INBOX_CONFIG_TEMPLATE = """\
# Generated by beets-inbox — inbox scratchpad library
directory: {inbox_path}
library: {db_path}

import:
  copy: false
  move: false
  write: false
  timid: false
  # Accept files even if no MusicBrainz match is found
  none: true

plugins: []
"""

_MAIN_CONFIG_TEMPLATE = """\
# Generated by beets-inbox — main library
directory: {library_path}
library: {db_path}

import:
  copy: true
  move: false
  write: true
  timid: false

plugins: []
"""


def write_inbox_config(config: Config) -> None:
    """Write inbox-beets.yaml if it doesn't exist yet."""
    cfg_path = config.beets_inbox_config
    if cfg_path.exists():
        return
    cfg_path.write_text(
        _INBOX_CONFIG_TEMPLATE.format(
            inbox_path=config.inbox_path,
            db_path=config.beets_inbox_db,
        )
    )


def write_main_config(config: Config, library_path: Path) -> None:
    """Write main-beets.yaml if it doesn't exist yet."""
    cfg_path = config.beets_main_config
    if cfg_path.exists():
        return
    cfg_path.write_text(
        _MAIN_CONFIG_TEMPLATE.format(
            library_path=library_path,
            db_path=config.beets_main_db,
        )
    )


# ── Subprocess helpers ────────────────────────────────────────────────────────

def _beet(
    beet_config: Path, *args: str, check: bool = True
) -> subprocess.CompletedProcess[str]:
    cmd = ["beet", "--config", str(beet_config), *args]
    return subprocess.run(cmd, capture_output=True, text=True, check=check)


# ── Inbox operations ──────────────────────────────────────────────────────────

def catalog_path(config: Config, path: Path) -> subprocess.CompletedProcess[str]:
    """Run inbox import on a file or directory (no copy/move/write)."""
    return _beet(
        config.beets_inbox_config, "import", "-A", "-q", str(path), check=False
    )


def remove_from_inbox(config: Config, path: Path) -> subprocess.CompletedProcess[str]:
    """Remove a file's entry (or all entries under a directory) from the inbox DB.

    Does NOT delete the source file — callers are responsible for that so the
    cleanup happens even when the item was never cataloged in the inbox DB.
    """
    query = f"path:{path}/" if path.is_dir() else f"path:{path}"
    return _beet(
        config.beets_inbox_config,
        "remove", "-f", query,
        check=False,
    )


# ── Main library import ───────────────────────────────────────────────────────

def import_to_library(
    config: Config,
    path: Path,
    tags: dict[str, Any],
) -> subprocess.CompletedProcess[str]:
    """Import a file/directory to the main library with user-confirmed tags.

    --set overrides any auto-matched MusicBrainz metadata, so user-confirmed
    tags take precedence regardless of what beets finds.
    """
    set_args: list[str] = []
    for key, value in tags.items():
        if value is not None:
            set_args += ["--set", f"{key}={value}"]
    # If artist is set but albumartist isn't, mirror artist → albumartist so
    # the library path uses the right value.
    if "artist" in tags and "albumartist" not in tags and tags.get("artist"):
        set_args += ["--set", f"albumartist={tags['artist']}"]
    return _beet(
        config.beets_main_config,
        "import", "-A", "-q",
        *set_args,
        str(path),
        check=False,
    )


# ── Inbox DB reader ───────────────────────────────────────────────────────────

def _inbox_conn(config: Config) -> sqlite3.Connection | None:
    db = config.beets_inbox_db
    if not db.exists():
        return None
    con = sqlite3.connect(str(db))
    con.row_factory = sqlite3.Row
    return con


# Beets DB column names we care about → the key name we expose in the tag dict.
# Note: beets uses "genres" (plural) for what we surface as "genre".
_WANTED_TAGS: dict[str, str] = {
    "title": "title",
    "artist": "artist",
    "album": "album",
    "albumartist": "albumartist",
    "genres": "genre",
    "year": "year",
    "track": "track",
}


def query_item_tags(config: Config, file_path: Path) -> dict[str, Any]:
    """Return tag dict for a specific file from the inbox beets DB.

    Only selects columns that exist in the DB schema (beets schema varies
    across versions). Maps beets column names to the keys the app uses
    (e.g. 'genres' → 'genre').
    """
    con = _inbox_conn(config)
    if con is None:
        return {}
    try:
        # Discover which columns actually exist in this DB's items table.
        schema_rows = con.execute("PRAGMA table_info(items)").fetchall()
        existing = {r["name"] for r in schema_rows}
        db_cols = sorted(col for col in _WANTED_TAGS if col in existing)
        if not db_cols:
            return {}

        col_sql = ", ".join(db_cols)

        # beets stores paths as bytes blobs; try exact match first, then a
        # suffix LIKE in case beets normalised or resolved symlinks.
        path_str = str(file_path)
        path_bytes = path_str.encode()
        row = con.execute(
            f"SELECT {col_sql} FROM items WHERE path = ?",  # noqa: S608
            (path_bytes,),
        ).fetchone()
        if row is None:
            row = con.execute(
                f"SELECT {col_sql} FROM items WHERE path LIKE ?",  # noqa: S608
                (f"%{path_str}".encode(),),
            ).fetchone()
        if row is None:
            return {}
        return {
            _WANTED_TAGS[col]: row[col]
            for col in db_cols
            if row[col] is not None and row[col] != ""
        }
    finally:
        con.close()


def query_all_inbox_paths(config: Config) -> set[str]:
    """Return the set of all file paths currently in the inbox beets DB."""
    con = _inbox_conn(config)
    if con is None:
        return set()
    try:
        rows = con.execute("SELECT path FROM items").fetchall()
        return {
            row["path"].decode() if isinstance(row["path"], bytes) else row["path"]
            for row in rows
        }
    finally:
        con.close()
