"""Beets CLI wrapper and inbox DB reader."""
from __future__ import annotations

import logging
import sqlite3
import subprocess
from pathlib import Path
from typing import Any

from ..config import Config

logger = logging.getLogger(__name__)

# ── Config generation ──────────────────────────────────────────────────────────

_INBOX_CONFIG_TEMPLATE = """\
# Generated by beets-inbox — inbox scratchpad library
directory: {inbox_path}
library: {db_path}

import:
  copy: false
  move: false
  write: false
  timid: false
  # Accept files even if no MusicBrainz match is found
  none: true
  # In quiet mode, fall back to embedded tags rather than skipping when
  # MusicBrainz confidence is below the auto-accept threshold
  quiet_fallback: asis

plugins: []
"""

_MAIN_CONFIG_TEMPLATE = """\
# Generated by beets-inbox — main library
directory: {library_path}
library: {db_path}

import:
  copy: true
  move: false
  write: true
  timid: false

plugins: []
"""


def write_inbox_config(config: Config) -> None:
    """Write inbox-beets.yaml, overwriting any existing file to stay in sync."""
    cfg_path = config.beets_inbox_config
    cfg_path.write_text(
        _INBOX_CONFIG_TEMPLATE.format(
            inbox_path=config.inbox_path,
            db_path=config.beets_inbox_db,
        )
    )


def write_main_config(config: Config, library_path: Path) -> None:
    """Write main-beets.yaml, overwriting any existing file to stay in sync."""
    cfg_path = config.beets_main_config
    cfg_path.write_text(
        _MAIN_CONFIG_TEMPLATE.format(
            library_path=library_path,
            db_path=config.beets_main_db,
        )
    )


# ── Subprocess helpers ────────────────────────────────────────────────────────

def _beet(
    beet_config: Path, *args: str, check: bool = True
) -> subprocess.CompletedProcess[str]:
    cmd = ["beet", "--config", str(beet_config), *args]
    return subprocess.run(cmd, capture_output=True, text=True, check=check)


# ── Inbox operations ──────────────────────────────────────────────────────────

def catalog_path(
    config: Config, path: Path, *, autotag: bool = True
) -> subprocess.CompletedProcess[str]:
    """Run inbox import on a file or directory (no copy/move/write).

    When autotag=True beets queries MusicBrainz and auto-accepts the best
    match in quiet mode.  When False, -A skips the lookup entirely.

    When path is a single file, --singleton (-s) is passed so beets does not
    group the file with siblings in the same directory.  When path is a
    directory, beets groups all files inside it as an album (the normal case
    for ZIP-extracted albums).
    """
    no_autotag = [] if autotag else ["-A"]
    singleton = ["-s"] if path.is_file() else []
    verbose = ["-v"] if autotag else []
    logger.info("catalog_path start  autotag=%-5s  %s", autotag, path)
    result = _beet(
        config.beets_inbox_config,
        *verbose, "import", "-q", *no_autotag, *singleton, str(path),
        check=False,
    )
    if result.returncode == 0:
        logger.info("catalog_path done   rc=0          %s", path)
    else:
        logger.warning("catalog_path failed rc=%d          %s", result.returncode, path)
    if result.stdout.strip():
        logger.info("beet stdout:\n%s", result.stdout.strip())
    if result.stderr.strip():
        logger.info("beet stderr:\n%s", result.stderr.strip())
    return result


def modify_item(
    config: Config, path: Path, tags: dict[str, Any]
) -> subprocess.CompletedProcess[str]:
    """Update tags for a file or directory in the inbox beets DB.

    For a directory, applies the tags to all items under it.
    """
    set_args = [f"{k}={v}" for k, v in tags.items() if v is not None]
    if not set_args:
        return subprocess.CompletedProcess([], 0, "", "")
    query = f"path:{path}/" if path.is_dir() else f"path:{path}"
    result = _beet(
        config.beets_inbox_config,
        "modify", "-y", *set_args, query,
        check=False,
    )
    if result.returncode != 0:
        logger.warning(
            "beet modify failed rc=%d  %s\n  stderr: %s",
            result.returncode, path, result.stderr.strip() or "(empty)",
        )
    return result


def remove_from_inbox(config: Config, path: Path) -> subprocess.CompletedProcess[str]:
    """Remove a file's entry (or all entries under a directory) from the inbox DB.

    Does NOT delete the source file — callers are responsible for that so the
    cleanup happens even when the item was never cataloged in the inbox DB.
    """
    query = f"path:{path}/" if path.is_dir() else f"path:{path}"
    return _beet(
        config.beets_inbox_config,
        "remove", "-f", query,
        check=False,
    )


# ── Main library import ───────────────────────────────────────────────────────

def import_to_library(
    config: Config,
    path: Path,
    tags: dict[str, Any],
) -> subprocess.CompletedProcess[str]:
    """Import a file/directory to the main library with user-confirmed tags.

    --set overrides any auto-matched MusicBrainz metadata, so user-confirmed
    tags take precedence regardless of what beets finds.
    """
    set_args: list[str] = []
    for key, value in tags.items():
        if value is not None:
            set_args += ["--set", f"{key}={value}"]
    # If artist is set but albumartist isn't, mirror artist → albumartist so
    # the library path uses the right value.
    if "artist" in tags and "albumartist" not in tags and tags.get("artist"):
        set_args += ["--set", f"albumartist={tags['artist']}"]
    return _beet(
        config.beets_main_config,
        "import", "-A", "-q",
        *set_args,
        str(path),
        check=False,
    )


# ── Inbox DB reader ───────────────────────────────────────────────────────────

def _inbox_conn(config: Config) -> sqlite3.Connection | None:
    db = config.beets_inbox_db
    if not db.exists():
        return None
    con = sqlite3.connect(str(db))
    con.row_factory = sqlite3.Row
    return con


# Beets DB column names we care about → the key name we expose in the tag dict.
# Note: beets uses "genres" (plural) for what we surface as "genre".
_WANTED_TAGS: dict[str, str] = {
    "title": "title",
    "artist": "artist",
    "album": "album",
    "albumartist": "albumartist",
    "genres": "genre",
    "year": "year",
    "track": "track",
}


def _beets_path(config: Config, file_path: Path) -> bytes:
    """Return the path bytes as beets stores them in the DB.

    Beets stores paths relative to the library 'directory' when the file is
    inside it, and as absolute paths otherwise.
    """
    try:
        rel = file_path.relative_to(config.inbox_path)
        return str(rel).encode()
    except ValueError:
        return str(file_path).encode()


def query_all_inbox_tags(config: Config) -> dict[str, dict[str, Any]]:
    """Return {absolute_path_str: tags_dict} for every file in the inbox beets DB.

    One DB query for the whole inbox — callers use this instead of calling
    query_item_tags per file.
    """
    con = _inbox_conn(config)
    if con is None:
        return {}
    try:
        schema_rows = con.execute("PRAGMA table_info(items)").fetchall()
        existing = {r["name"] for r in schema_rows}
        db_cols = sorted(col for col in _WANTED_TAGS if col in existing)
        col_sql = ", ".join(["path", *db_cols]) if db_cols else "path"
        rows = con.execute(f"SELECT {col_sql} FROM items").fetchall()  # noqa: S608
        result: dict[str, dict[str, Any]] = {}
        for row in rows:
            p_raw = row["path"]
            raw = p_raw.decode() if isinstance(p_raw, bytes) else p_raw
            p = Path(raw)
            if not p.is_absolute():
                p = config.inbox_path / p
            tags: dict[str, Any] = {
                _WANTED_TAGS[col]: row[col]
                for col in db_cols
                if row[col] is not None and row[col] != ""
            }
            result[str(p)] = tags
        return result
    finally:
        con.close()


def query_item_tags(config: Config, file_path: Path) -> dict[str, Any]:
    """Return tag dict for a specific file from the inbox beets DB.

    Only selects columns that exist in the DB schema (beets schema varies
    across versions). Maps beets column names to the keys the app uses
    (e.g. 'genres' → 'genre').
    """
    con = _inbox_conn(config)
    if con is None:
        return {}
    try:
        # Discover which columns actually exist in this DB's items table.
        schema_rows = con.execute("PRAGMA table_info(items)").fetchall()
        existing = {r["name"] for r in schema_rows}
        db_cols = sorted(col for col in _WANTED_TAGS if col in existing)
        if not db_cols:
            return {}

        col_sql = ", ".join(db_cols)
        path_bytes = _beets_path(config, file_path)
        row = con.execute(
            f"SELECT {col_sql} FROM items WHERE path = ?",  # noqa: S608
            (path_bytes,),
        ).fetchone()
        if row is None:
            return {}
        return {
            _WANTED_TAGS[col]: row[col]
            for col in db_cols
            if row[col] is not None and row[col] != ""
        }
    finally:
        con.close()


def query_all_inbox_paths(config: Config) -> set[str]:
    """Return absolute path strings for all files in the inbox beets DB.

    Beets stores paths relative to the library directory for in-library files,
    so we resolve them back to absolute paths for consistent comparison.
    """
    con = _inbox_conn(config)
    if con is None:
        return set()
    try:
        rows = con.execute("SELECT path FROM items").fetchall()
        result: set[str] = set()
        for row in rows:
            p_raw = row["path"]
            raw = p_raw.decode() if isinstance(p_raw, bytes) else p_raw
            p = Path(raw)
            if not p.is_absolute():
                p = config.inbox_path / p
            result.add(str(p))
        return result
    finally:
        con.close()
