"""Beets CLI wrapper and inbox DB reader."""
from __future__ import annotations

import sqlite3
import subprocess
from pathlib import Path
from typing import Any

from ..config import Config

# ── Config generation ──────────────────────────────────────────────────────────

_INBOX_CONFIG_TEMPLATE = """\
# Generated by beets-inbox — inbox scratchpad library
directory: {inbox_path}
library: {db_path}

import:
  copy: false
  move: false
  write: false
  timid: false
  # Accept files even if no MusicBrainz match is found
  none: true

plugins: []
"""

_MAIN_CONFIG_TEMPLATE = """\
# Generated by beets-inbox — main library
directory: {library_path}
library: {db_path}

import:
  copy: true
  move: false
  write: true
  timid: false

plugins: []
"""


def write_inbox_config(config: Config) -> None:
    """Write inbox-beets.yaml if it doesn't exist yet."""
    cfg_path = config.beets_inbox_config
    if cfg_path.exists():
        return
    cfg_path.write_text(
        _INBOX_CONFIG_TEMPLATE.format(
            inbox_path=config.inbox_path,
            db_path=config.beets_inbox_db,
        )
    )


def write_main_config(config: Config, library_path: Path) -> None:
    """Write main-beets.yaml if it doesn't exist yet."""
    cfg_path = config.beets_main_config
    if cfg_path.exists():
        return
    cfg_path.write_text(
        _MAIN_CONFIG_TEMPLATE.format(
            library_path=library_path,
            db_path=config.beets_main_db,
        )
    )


# ── Subprocess helpers ────────────────────────────────────────────────────────

def _beet(
    beet_config: Path, *args: str, check: bool = True
) -> subprocess.CompletedProcess[str]:
    cmd = ["beet", "--config", str(beet_config), *args]
    return subprocess.run(cmd, capture_output=True, text=True, check=check)


# ── Inbox operations ──────────────────────────────────────────────────────────

def catalog_path(config: Config, path: Path) -> subprocess.CompletedProcess[str]:
    """Run inbox import on a file or directory (no copy/move/write)."""
    return _beet(
        config.beets_inbox_config, "import", "-A", "-q", str(path), check=False
    )


def remove_from_inbox(config: Config, path: Path) -> subprocess.CompletedProcess[str]:
    """Remove a file's entry from the inbox DB and delete the source file."""
    return _beet(
        config.beets_inbox_config,
        "remove", "-d", "-f", f"path:{path}",
        check=False,
    )


# ── Main library import ───────────────────────────────────────────────────────

def import_to_library(
    config: Config,
    path: Path,
    tags: dict[str, Any],
) -> subprocess.CompletedProcess[str]:
    """Import a file/directory to the main library with user-confirmed tags.

    --set overrides any auto-matched MusicBrainz metadata, so user-confirmed
    tags take precedence regardless of what beets finds.
    """
    set_args: list[str] = []
    for key, value in tags.items():
        if value is not None:
            set_args += ["--set", f"{key}={value}"]
    # If artist is set but albumartist isn't, mirror artist → albumartist so
    # the library path uses the right value.
    if "artist" in tags and "albumartist" not in tags and tags.get("artist"):
        set_args += ["--set", f"albumartist={tags['artist']}"]
    return _beet(
        config.beets_main_config,
        "import", "-A", "-q",
        *set_args,
        str(path),
        check=False,
    )


# ── Inbox DB reader ───────────────────────────────────────────────────────────

def _inbox_conn(config: Config) -> sqlite3.Connection | None:
    db = config.beets_inbox_db
    if not db.exists():
        return None
    con = sqlite3.connect(str(db))
    con.row_factory = sqlite3.Row
    return con


def query_item_tags(config: Config, file_path: Path) -> dict[str, Any]:
    """Return tag dict for a specific file from the inbox beets DB."""
    con = _inbox_conn(config)
    if con is None:
        return {}
    try:
        # beets stores paths as bytes blobs
        path_bytes = str(file_path).encode()
        row = con.execute(
            """SELECT title, artist, album, albumartist, genre, year, track
               FROM items WHERE path = ?""",
            (path_bytes,),
        ).fetchone()
        if row is None:
            return {}
        return {k: row[k] for k in row if row[k] is not None and row[k] != ""}
    finally:
        con.close()


def query_all_inbox_paths(config: Config) -> set[str]:
    """Return the set of all file paths currently in the inbox beets DB."""
    con = _inbox_conn(config)
    if con is None:
        return set()
    try:
        rows = con.execute("SELECT path FROM items").fetchall()
        return {
            row["path"].decode() if isinstance(row["path"], bytes) else row["path"]
            for row in rows
        }
    finally:
        con.close()
